### ISSUE TITLE
嗨嗨 Ukagaka好像掛了Q___Q

### ISSUE THREAD

**Issue by NatLee** [morris821028/mblog-ukagaka#1]
https://spreadsheets.google.com/feeds/list/0ArRwmWo93u-mdG93a2dkSWxIbHEzZjRIeDdxZXdsU1E/od6/public/values?alt=json
她都不肯學新東西了
不管什麼姿勢輸入都是空白

chrome的報錯訊息是
<code>XMLHttpRequest cannot load https://docs.google.com/forms/d/*************/formResponse
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.</code>

m(_ _)m

**Comment by NatLee** [comment]
解決傳送null的問題了 已pull request

雖然還是 **No 'Access-Control-Allow-Origin' header is present on the requested resource.**
但功能可以work了 :+1: 

然後 統計詞彙數量 跟 學的新詞 要刷新頁面才會生效XD ((畢竟是用get的方式解決ww
不知道有沒有辦法讓它自己reload就好 :coffee:

**Comment by morris821028** [comment]
目前只能往同一個表單送，要有免費好用 (單純使用前端 js 驅動) 的方案不容易。

最近在想是不是該往 live2D 前進。

**Comment by NatLee** [comment]
雖然只能送一個表單，但應該是可以開很多表單分頁(?)來接response
不過這我就沒試過惹

live2D 是做類似像動畫那樣然後偵測物件移動？
好像很好玩欸YEEEEEEE

**Comment by morris821028** [comment]
類似。

就我的理解，模組部份要靠別的軟體做好，寫成 .mtn 檔案。檔案內部主要是節點座標。座標和座標之間移動就靠 WebGL 進行微調，看起來就像是動畫一樣。

現在已經將 ukagaka 模組部份用額外的 json 方式取得，不依賴 jquery 套件參數。

**Comment by NatLee** [comment]
我去google了一下XD
發現真的挺酷的 可是模組的editor好貴QQ
大大以後要做的時候 我一定會去朝聖XDDDD
