### ISSUE TITLE
Hi, can Hexo blog add this web plugin?

### ISSUE THREAD

**Issue by woshiamiaojiang** [morris821028/mblog-ukagaka#3]
Hi, can Hexo blog add this web plugin? If the answer is yes, I will appreciate it that you could give me more details about the procedure.

**Comment by morris821028** [comment]
This plugin needs a storage backend. Now, it works with google sheets API. This service is stopped, or out of date. You need to find the newest API to store request if the visitor wanted to add a new statement for ukagaka. If you don't want to provide "add statements" for any visitor, it can be wrapped to a hexo's plugin.

How do you feel?

**Comment by woshiamiaojiang** [comment]
I see. Many thanks for your elaborate details.
